### ISSUE TITLE
clear the list cause crash

### ISSUE THREAD

**Issue by njleonzhang** [gongwen/MarqueeViewLibrary#9]
崩溃的伪代码：
```
list.add(****)
list.add(****)
list.add(****)

marqueeFactory().resetData(list); <----正常显示
list.clear();
marqueeFactory().resetData(list); <----正常
list.add(****);
marqueeFactory().resetData(list);   <---crash
```
崩溃log:
```
05-17 19:25:42.153 12007-12007/com.zywulian.smartlife E/AndroidRuntime: FATAL EXCEPTION: main Process: com.zywulian.smartlife, PID: 12007
        java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3524)
            at android.view.View.draw(View.java:16681)
            at android.view.View.updateDisplayListIfDirty(View.java:15622)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
            at android.view.View.updateDisplayListIfDirty(View.java:15573)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:3088)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2892)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2504)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1335)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6869)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
            at android.view.Choreographer.doCallbacks(Choreographer.java:696)
            at android.view.Choreographer.doFrame(Choreographer.java:631)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
            at android.os.Handler.handleCallback(Handler.java:815)
            at android.os.Handler.dispatchMessage(Handler.java:104)
          at android.os.Looper.
```

**Comment by njleonzhang** [comment]
这是一个android 6.0上的一个比较常见的问题。
[stack上有解决方案](http://stackoverflow.com/questions/41821727/getting-nullpointerexception-attempt-to-read-from-field-int-android-view-view)
我改了一下你的源码现在问题解决了，马上给你提个PR，你看下要不要merge
